markdown:         redcarpet
pygments:         true
permalink:        pretty
exclude:          ['less','vendor','*.json','Gruntfile.js','bower_components','node_modules']
source:           ./src
destination:      ./_gh_pages
encoding:         UTF-8
title:            drawer
discription:      jquery plugin for easily implement a sliding drawer into your website.
url:              http://git.blivesta.com/drawer/
repo:             drawer
repo_url:         https://github.com/blivesta/drawer
author:           blivesta
author_url:       http://blivesta.com
current_version:  1.5.1
twitter:          blivesta
tag:              
git_fork_btn:     http://ghbtns.com/github-btn.html?user=blivesta&amp;repo=drawer&amp;type=fork&amp;count=true
git_star_btn:     http://ghbtns.com/github-btn.html?user=blivesta&amp;repo=drawer&amp;type=watch&amp;count=true
